function create_itr_figure(X1, YMatrix1)
%CREATEFIGURE(X1, YMATRIX1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 14-Mar-2018 17:13:41

% Create figure
figure1 = figure;

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot(X1,YMatrix1);

% Create xlabel
xlabel('No. of MSs');

% Create ylabel
ylabel('Avrage number of iterations to reach the optimum ');

box(axes1,'on');
% Set the remaining axes properties
set(axes1,'FontSize',14);
